name: CI

on:
  push:
    branches: [main, teste]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Change to Repository Directory
        run: cd $GITHUB_WORKSPACE  # Change to the root directory of the repository

      - name: Push to Another Repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: '.'  # Push all files in the root directory
          destination-github-username: 'markfinn0'
          destination-repository-name: 'teste_mobile'
          user-email: 'marquinhossouzarodrigueslive@gmail.com'
          target-branch: main
